spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  cache:
    type: redis
  application:
    name: education
mybatis-plus:
  type-aliases-package: com.education.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/**/*.xml
